#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/redmine-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN

\`\`\`

Return Issue link in Markdown format.


Example:

\`\`\`bash

  $BIN 123

\`\`\`

  [#123](https://redmine.gcoop.coop/issues/123)

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage
REGEX='^[0-9]+$'

if [[ -z "$1" ]]
then
  ISSUE="$(get_issue_from_jrnl)"
else
  ISSUE="$1"
fi

[[ -z "$ISSUE" ]] && die "EMPTY ISSUE"
[[ "$ISSUE" =~ $REGEX ]] || die "INVALID ISSUE $ISSUE"

echo "[#$ISSUE]($API_URL/issues/$ISSUE)"
