#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2016 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

die ()
{
  echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
}

CONFIG="$HOME/.redmine.conf"
[[ ! -e "$CONFIG" ]] && die "not found file: $CONFIG"

eval $(sed '/:/!d;/^ *#/d;s/:/ /;' < "$CONFIG" | while read -r key val
do
    str="$key='$val'"
    echo "$str"
done)

[[ -z "$API_URL" ]] && die "empty URL"
[[ -z "$API_KEY" ]] && die "empty KEY"
[[ -z "$STATUS_FIXED" ]] && die "undefined STATUS_FIXED"
[[ ! -z "$DEFAULT_ASSIGNED_TO_ID" ]] && ASSIGNED_TO_ID="$DEFAULT_ASSIGNED_TO_ID"

[[ -z "$1" ]] && die "empty ISSUE_ID"
VALID_ISSUE_ID=$(echo "$1" | egrep -o "^[0-9]+$")

[[ "$VALID_ISSUE_ID" != "$1" ]] && die "invalid ISSUE_ID"
ISSUE_ID="$1"

[[ -z "$2" ]] && die "empty SUBJECT"
SUBJECT="$(echo "$2" | tr -d '"')"

JSON_FILE=$(mktemp)

JSON=$(cat << EOF
{
    "issue": {
      "subject": "$SUBJECT"
    }
}
EOF
)

echo "$JSON" > "$JSON_FILE"

H1='"Content-Type: application/json"'
H2='"X-Redmine-API-Key: '$API_KEY'"'
URL="$API_URL/issues/${ISSUE_ID}.json"

CURL_PROXY=''
[[ ! -z "$REDMINE_PROXY_SOCKS" ]] && CURL_PROXY="--socks5 $REDMINE_PROXY_SOCKS"

echo curl $CURL_PROXY -s -k -H "$H1" -X PUT --data "@$JSON_FILE" -H "$H2" "$URL" | bash && rm -f "$JSON_FILE"
