#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2016 Magalí Fernandez Valdez <magui@gcoop.coop>
#                    Osiris Alejandro Gómez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

die ()
{
  echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
}

[[ -z "$1" ]] && die "empty FILE"
FILE="$1"
[[ ! -e "$FILE" ]] && "not found file: $FILE"

IFS='|'
while read SUBJECT DESCRIPTION
do

  [[ -z "$SUBJECT" ]] && continue

  if [ -z "$DESCRIPTION" ]
  then
    redmine-new-issue "$SUBJECT"
  else
    redmine-new-issue "$SUBJECT" "$DESCRIPTION"
  fi

done < "$FILE"

