#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2016 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

die ()
{
  echo "ERROR $1" && exit 1
}

b=jrnl
which $b 2>/dev/null >/dev/null
OK=$(echo $?)
[[ "$OK" -ne 0 ]] && die "not found: $b try: sudo pip install $b"

[[ -z "$1" ]]

redmine-add-comment "$1" "$(jrnl -1 | head -1) \\n<pre>$(jrnl -1 | tail -n +2 | sed 's/^|//g' | sed ':a;N;$!ba;s/\n/\\n/g')</pre>"

