#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2016 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

die ()
{
  echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
}

CONFIG="$HOME/.redmine.conf"
[[ ! -e "$CONFIG" ]] && die "not found file: $CONFIG"

for b in curl jq
do
  which $b 2>/dev/null >/dev/null
  OK="$?"
  [[ "$OK" -ne 0 ]] && die "not found: $b try: sudo apt-get install $b"
done

eval $(sed '/:/!d;/^ *#/d;s/:/ /;' < "$CONFIG" | while read -r key val
do
    str="$key='$val'"
    echo "$str"
done)

[[ -z "$API_URL" ]] && die "empty URL"
[[ -z "$API_KEY" ]] && die "empty KEY"

[[ -z "$1" ]] && die "empty ISSUE_ID"
ISSUE_ID="$1"

H1='"Content-Type: application/json"'
H2='"X-Redmine-API-Key: '$API_KEY'"'
URL="$API_URL/issues/${ISSUE_ID}.json"

JQ=$(cat  << EOF
{
issue: .issue.id,
parent: .issue.parent,
tracker: .issue.tracker.name,
status: .issue.status.name,
priority: .issue.priority.name,
project: .issue.project.name,
subject: .issue.subject,
updated_on: .issue.updated_on,
spent_hours: .issue.spent_hours,
done_ratio: .issue.done_ratio,
assigned_to: .issue.assigned_to,
category: .issue.category,
custom_fields: .issue.custom_fields,
description: .issue.description
}
EOF
)

echo
echo curl -s -k -H "$H1" -X GET -H "$H2" "$URL" \
  | bash \
  | jq ". | $JQ" \
  | jq .
