#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2016 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

die ()
{
  echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
}

COMMIT=1
# FIXME diff numbers of commits from hash
if [[ ! -z "$2" ]]
then
  BODY="$(git show -p --name-only "$2")"
else
  BODY=$(git log -n"$COMMIT" --name-only)
fi

[[ -z "$BODY" ]] && die "EMPTY LOG"

ISSUE=$(echo "$BODY" | egrep -wo "#[0-9]+" | egrep -o "[0-9]+" | head -1)

if [[ -z "$ISSUE" ]]
then
  # not found #ISSUE in BODY
  if [[ -z "$1" ]]
  then
    die "empty issue"
  else
    ISSUE="$1"
  fi
fi

SC="$(git log -1 --format='%h')"
LC="$(git log -1 --format='%H')"
ORIGIN="$(git remote get-url origin)"

if [[ "$ORIGIN" =~ .*:/.* ]]
then
  URL="https://$(echo "$ORIGIN" | tr -d ':')"
else
  URL="$ORIGIN"
fi

LINK="$(printf "commit: \"%s\":%s/commit/%s\n" "$SC" "$URL" "$LC")"
redmine-add-comment "$ISSUE" "<pre>$BODY</pre>\\n\\n${LINK}"

