#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/redmine-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN

\`\`\`

Return SUBJECT URL_IN_MARKDOWN_FORMAT

Example:

\`\`\`bash

  $BIN 1234

  Example of subject [#1234](https://redmine.example.com/issues/1234)

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

if [[ -z "$1" ]]
then
  ISSUE="$(get_issue_from_jrnl)"
else
  ISSUE="$1"
fi

[[ -z "$ISSUE" ]] && die "EMPTY ISSUE"

redmine-show-issue "$ISSUE"             \
  | jq -r '. | "\(.issue) \(.subject)"' \
  | while read -r I S
    do
      U="$(issue2md "$I")"
      printf "%s %s\\n" "$S" "$U"
    done
