#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2016 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

die ()
{
  echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
}

CONFIG="$HOME/.redmine.conf"
[[ ! -e "$CONFIG" ]] && die "not found file: $CONFIG"

ISSUE=$(redmine-add-comment-from-jrnl | egrep -o "#[0-9]+\ ")
OK=$?
[[ "$OK" -ne 0 ]] && die "error when add comment"
[[ -z "$ISSUE" ]] && die "empty ISSUE"

ISSUE_ID=$(echo "$ISSUE" | egrep -o "[0-9]+")
[[ -z "$ISSUE_ID" ]] && die "empty ISSUE_ID"

VALID_ISSUE_ID=$(echo "$ISSUE_ID" | egrep -o "^[0-9]+$")
[[ "$VALID_ISSUE_ID" != "$ISSUE_ID" ]] && die "invalid ISSUE_ID"

redmine-fix "$ISSUE_ID"
