#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2016 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

die ()
{
  echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
}

[[ -z "$1" ]] && die "EMPTY FILE"
[[ ! -e "$1" ]] && die "NOT FOUND FILE $2"
FILE="$1"

HEAD=$(head -1 "$FILE" | tr '"' "'" | sed 's/\x1B\[[0-9;]*[JKmsu]//g')
ISSUE=$(echo "$HEAD" | egrep -wo "#[0-9]+" | egrep -o "[0-9]+")

if [ -z "$ISSUE" ]
then
  # not found #ISSUE in header of file
  if [ -z "$2" ]
  then
    die "empty issue"
  else
    ISSUE="$2"
  fi
fi

BODY=$(tail -n +2 "$FILE")

if [ -z "$BODY" ]
then
  redmine-add-comment "$ISSUE" "$HEAD \\n"
else
  redmine-add-comment "$ISSUE" "$HEAD \\n<pre>$BODY</pre>"
fi

