#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC2012

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/redmine-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN

\`\`\`

It searches the bash history for the las redmine commands executed.

Requirements:

You need in \`~/.bashrc\` the following line:

\`\`\`bash

  export HISTTIMEFORMAT='%Y-%m-%d %H:%M '

\`\`\`

Example:

\`\`\`bash

  $BIN

\`\`\`

	10:35 redmine-from-jrnl
	10:42 redmine-add-comment-from-git-log 48605
	11:26 redmine-assign-to 48608 osiris
	11:30 redmine-from-jrnl
	11:32 redmine-needs-feedback 48608
	12:08 redmine-timediff-last-comment

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

TODAY="$(date +%F)"
DATE="$TODAY"

cd "$DIR_BIN" || die "cannot change to directory $DIR_BIN"

BIN_LIST="$DIR_BIN/.redmine-bin"

# FIXME regenerate after x time (maybe on pre-commit?)
if [[ ! -e "$BIN_LIST" ]]
then

  ls -1 redmine-*                               \
  | sed -e 's/^redmine/:\[0-9\]\{2\} redmine/g' \
  | grep -v redmine-history                     > "$BIN_LIST"

fi

[[ -z "$1" ]] || DATE="$1"

# https://askubuntu.com/questions/546556/how-can-i-use-history-command-in-a-bash-script#546560
HISTFILE="$HOME/.bash_history"
HISTTIMEFORMAT='%Y-%m-%d %H:%M '
set -o history
history                  \
  | grep "$DATE"         \
  | cut -c 19-           \
  | grep -Ef "$BIN_LIST" \
  | sort -u

history -cw
