#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2016 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

die ()
{
  echo -e "\e[31m[ERROR]\e[0m $1" && exit 1
}

b=jrnl
which $b 2>/dev/null >/dev/null
OK="$?"
[[ "$OK" -ne 0 ]] && die "not found: $b try: sudo pip install $b"

if [[ ! -z "$2" ]]
then
  VALID_MINUTES=$(echo "$2" | egrep -o "^[0-9]+$")
  [[ -z "$VALID_MINUTES" ]] && die "empty MINUTES"
  [[ "$VALID_MINUTES" != "$2" ]] && die "invalid MINUTES: $MINUTES"
  MINUTES="$2"
fi

[[ -z "$1" ]] && die "empty FILENAME"
FILE="$1"

[[ ! -e "$FILE" ]] && die "not found $FILE"

FOOT=$(grep '@' "$FILE" | tail -1)
TIME=$(echo "$FOOT" | egrep -o "^\s*@ [0-9]{2}:[0-9]{2} hs" | awk '{print $2}' | egrep -o "[0-9]{2}:[0-9]{2}")

if [[ ! -z "$TIME" ]]
then
  HH=$(echo "$TIME" | cut -d : -f1 | sed -e 's/^0\+//g')
  MM=$(echo "$TIME" | cut -d : -f2 | sed -e 's/^0\+//g')
  [[ -z "$HH" ]] && HH=0
  [[ -z "$MM" ]] && MM=0
  H2M=$((HH*60+MM))
  VALID_MINUTES=$(echo "$H2M" | egrep -o "^[0-9]+$")
  [[ -z "$VALID_MINUTES" ]] && die "empty MINUTES"
  MINUTES="$H2M"
  [[ -z "$MINUTES" ]] && die "invalid MINUTES in file"
fi

HEAD=$(head -1 "$FILE")
ISSUE=$(echo "$HEAD" | grep -woE "#[0-9]+" | tr -d '#' | grep -oE "[0-9]+" | head -1)

HEAD_T=18
HEAD_M=255
HEAD_I=${#ISSUE}
HEAD_N=$(( HEAD_T + HEAD_I + 2))

COMMENTS=$(echo "$HEAD" | cut -c $HEAD_N-$HEAD_M)

[[ -z "$COMMENTS" ]] && die "empty COMMENTS"

if [[ -z "$ISSUE" ]]
then
  # not found #ISSUE in header of journal
  if [[ -z "$3" ]]
  then
    die "empty issue"
  else
    ISSUE="$3"
  fi
fi

redmine-time-entry "$MINUTES" "$ISSUE" "$URL_COMMIT\\n$COMMENTS"
